### ISSUE TITLE
Shims.zig not in build.zig.zon path

### ISSUE THREAD

**Issue by chrscchrn** [castholm/zigglgen#16]
![Screenshot from 2024-10-18 13-42-22](https://github.com/user-attachments/assets/e1d3c683-628d-4705-8ce0-324c5a2062e5)
Running into an issue where the shims.zig is not found in my zig cache. Looks like it's missing from the file paths in the zig manifest.

**Comment by chrscchrn** [comment]
https://github.com/castholm/zigglgen/pull/17

**Comment by chrscchrn** [comment]
Zig version: 0.13.0
OS: Ubuntu 24.04

**Comment by castholm** [comment]
33ee1647f577e057ca05dac568101a0f42e590a1
