### ISSUE TITLE
Enforce debug build of generator executable

### ISSUE THREAD

**Issue by terraquad** [castholm/zigglgen#21]
I think it would be smart to always build the generator in debug mode, as it doesn't really matter how fast it is when compiling your program in release mode.
Right now, whenever you try to build your application in release mode, Zig builds the generator executable in release mode as well, which takes up plenty of compile time.

The fix is simply to edit this line:

https://github.com/castholm/zigglgen/blob/5e9e161202e3db77094bd237538a1c6f0cd353f6/build.zig#L5

to be:

```zig
const optimize = std.builtin.OptimizeMode.Debug;
```

**Comment by castholm** [comment]
701f41808086411f14d3bc2d87fc0b14bd09ceba
