### ISSUE TITLE
Use the std.Build.dependency() system instead of `generateBindingsModule`

### ISSUE THREAD

**Issue by terraquad** [castholm/zigglgen#23]
Before I start working on a PR, I wanted to ask if we should switch from the `zigglgen.generateBindingsModule` API to the more commonly used `b.dependency` API. To the user, this would look like this:

```zig
// current API
pub fn build(b: *std.Build) void {
    // ...
    const gl_module = zigglgen.generateBindingsModule(b, .{
        .api = .gl,
        .version = .@"4.3",
        .profile = .core,
        .extensions = &.{},
    });
    exe.root_module.addImport("gl", gl_module);
}
```

```zig
// proposed API
pub fn build(b: *std.Build) void {
    // ...
    const gl_dep = b.dependency("zigglgen", .{
        .api = .gl,
        .version = .@"4.3",
        .profile = .core,
        .extensions = &.{},
    });
    exe.root_module.addImport("gl", gl_dep.module("gl"));
}
```

Internally it would look (roughly) like this (I'm just writing this in GitHub and didn't test this):

```zig
pub fn build(b: *std.Build) void {
    const api = b.option(GeneratorOptions.Api, "api", "API variant") orelse {
        // somehow check if running as a dependency, as the main generator exe wouldn't need these options
        const fail = b.addFail("Option 'api' is required!");
        b.getInstallStep().dependOn(&fail.step);
        return;
    };
    const version = b.option(GeneratorOptions.Version, "version", "API version") orelse {
        // see comment above in orelse block
        const fail = b.addFail("Option 'version' is required!");
        b.getInstallStep().dependOn(&fail.step);
        return;
    };
    const profile = b.option(GeneratorOptions.Profile, "profile", "API profile");
    const extensions = b.option([]const GeneratorOptions.Extension, "extensions", "API extensions") orelse &.{};

    const module = b.addModule("gl", .{
        .root_source_file = generateBindingsSourceFile(b, .{
            .api = api,
            .version = version,
            .profile = profile,
            .extensions = extensions,
        }),
    });
    _ = module;
}
```

**Comment by terraquad** [comment]
After some experimenting, while a little hacky, we could check if zigglgen is being built directly or as a dependency like this:

```zig
pub fn build(b: *std.Build) void {
    // ...
    if (std.mem.endsWith(u8, b.dep_prefix, "zigglgen.")) { // note that "zigglgen" must be the name of the dependency in build.zig.zon
        // running as dependency
    } else {
        // running directly
    }
}
```

**Comment by castholm** [comment]
I think this is an interesting idea that might be worth exploring, but before you start working on anything I would first like to ask, do you have any projects or practical use cases that motivate exposing everything via `b.dependency` over `@import`ing the build.zig?

The main downside of `b.dependency` over `@import("zigglgen").generateBindingsModule` is that your IDE won't be able to provide completions for the duck-typed `anytype` argument, so you need to check the docs to figure out which options to pass. `b.dependency` is also currently quite undercooked; for example, even though Zig master lets you declare an enum list option with something like `b.option([]const GeneratorOptions.Extension, ...)`, you can't actually pass an enum list like `&.{ .ARB_clip_control, .NV_scissor_exclusive }` to `b.dependency`. So speaking in terms of developer UX, importing the strongly typed functions is the better, more discoverable and less error-prone experience.

**Comment by terraquad** [comment]
The main advantage would be that it uses the same API as other dependencies, making it more straightforward to set up.

I agree with you that the anytype parameter in b.dependency doesn't get type completion from zls, however from my experience it already works pretty badly with extensions because the Extension enum is so large.

What do you mean by "you can't pass enum lists to b.dependency"? I haven't tested the code, but I assumed it would work...

**Comment by castholm** [comment]
I'm going to close this as not wanted/planned for now. It's simply worse developer UX and does not appear to enable any important use cases that are not currently possible. Users should get used to the idea that Zig dependencies can be used both via `b.dependency` and `@import`.

I might consider revisiting the idea in the future if the Zig build system and APIs improve.
